using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace AutoLayoutSwitch
{
    public class KeyboardHook : IDisposable
    {
        private Win32.LowLevelKeyboardProc _proc;
        private IntPtr _hookID = IntPtr.Zero;
        private Func<int, int, bool> _callback;

        public KeyboardHook(Func<int, int, bool> callback)
        {
            _callback = callback;
            _proc = HookCallback;
            _hookID = SetHook(_proc);
        }

        private IntPtr SetHook(Win32.LowLevelKeyboardProc proc)
        {
            using (Process curProcess = Process.GetCurrentProcess())
            using (ProcessModule curModule = curProcess.MainModule!)
            {
                return Win32.SetWindowsHookEx(Win32.WH_KEYBOARD_LL, proc,
                    Win32.GetModuleHandle(curModule.ModuleName), 0);
            }
        }

        private unsafe IntPtr HookCallback(int nCode, IntPtr wParam, IntPtr lParam)
        {
            if (nCode >= 0 && wParam == (IntPtr)Win32.WM_KEYDOWN)
            {
                Win32.KBDLLHOOKSTRUCT* kbStruct = (Win32.KBDLLHOOKSTRUCT*)lParam;
                
                // Ignore injected inputs (generated by SendInput) to avoid infinite loops
                if ((kbStruct->flags & 0x10) != 0) // LLKHF_INJECTED
                {
                    return Win32.CallNextHookEx(_hookID, nCode, wParam, lParam);
                }

                // If callback returns true, suppress the key
                if (_callback(kbStruct->vkCode, kbStruct->scanCode))
                {
                    return (IntPtr)1;
                }
            }
            return Win32.CallNextHookEx(_hookID, nCode, wParam, lParam);
        }

        public void Dispose()
        {
            Win32.UnhookWindowsHookEx(_hookID);
        }
    }
}
